// web/wazz/src/AppHeader.tsx
import {
    GIT_BRANCH_STR,
    GIT_HASH_STR,
    GIT_LONG_STR,
    VERSION_MAJOR,
    VERSION_MINOR
} from "./GitBuild.ts";
import {Nav, Navbar} from "react-bootstrap";
import {Link, useLocation} from "react-router-dom";
import {useEffect} from "react";
import {GTagPageView} from "./GTagPageView.ts";

function AppHeader() {
    const location = useLocation();

    useEffect(() => {
        GTagPageView(
            location.pathname === "/" ? "dashboard" : location.pathname.replaceAll("/", ""),
            window.location.href,
            location.pathname,
        )
    }, [location]);

    const isActive = (path: string) => {
        if (path === "/") {
            return location.pathname === path;
        } else {
            return location.pathname.startsWith(path);
        }
    };

  return (
    <Navbar expand="md" bg="dark" data-bs-theme="dark" >
        <Navbar.Brand >
            Randall Trains Status
        </Navbar.Brand>
        <div className="flex-grow-1">
            <Nav className="nav-font-size flex-row justify-content-start justify-content-md-start" variant="underline">
                <Nav.Link as={Link} to="/"     active={isActive("/"    )}>Dashboard</Nav.Link>
                <Nav.Link as={Link} to="/perf" active={isActive("/perf")}>Performance</Nav.Link>
            </Nav>
        </div>
        <Navbar.Toggle aria-controls="text-nav-info" />
        <Navbar.Collapse id="text-nav-info" className="navbar-detail justify-content-end">
            <Navbar.Text>
                <a href="https://www.alfray.com/trains/randall/" target="_blank">The Randall Museum Model Railroad</a>
                <br/>
                <Link to="/statz">σ</Link>
                { ' ' }
                <Link to="/legacy">λ</Link>
                { ' ' }
                {`v${VERSION_MAJOR}.${VERSION_MINOR}, `}
                { ' ' }
                <span className="gitinfo" title={GIT_LONG_STR}>
                    <a href={`https://github.com/model-railroad/conductor/tree/${GIT_BRANCH_STR}`} target="_blank">
                        build {GIT_BRANCH_STR}
                    </a>
                    { " @ " }
                    <a href={`https://github.com/model-railroad/conductor/commit/${GIT_HASH_STR}`} target="_blank">
                        {GIT_HASH_STR}
                    </a>
                </span>
            </Navbar.Text>
        </Navbar.Collapse>
    </Navbar>
  )
}

export default AppHeader

// web/v-wazz/src/components/AppHeader.vue
<script setup lang="ts">
import {BCollapse, BLink, BNav, BNavbar, BNavbarBrand, BNavbarToggle, BNavItem, BNavText} from "bootstrap-vue-next";
import {GIT_BRANCH_STR, GIT_HASH_STR, GIT_LONG_STR, VERSION_MAJOR, VERSION_MINOR} from "../GitBuild.ts";
</script>

<template>
  <BNavbar toggleable="md" variant="dark" data-bs-theme="dark" >
    <BNavbarBrand>
      Randall Trains Status
    </BNavbarBrand>
    <div class="flex-grow-1">
      <BNav underline class="nav-font-size flex-row justify-content-start justify-content-md-start">
        <BNavItem :active="true">Dashboard</BNavItem>
        <BNavItem :active="false" disabled>Performance</BNavItem>
      </BNav>
    </div>
    <BNavbarToggle target="text-nav-info" />
    <BCollapse is-nav id="text-nav-info" class="navbar-detail justify-content-end">
      <BNavText>
        <a href="https://www.alfray.com/trains/randall/" target="_blank">The Randall Museum Model Railroad</a>
        <br/>
        <BLink to="/statz">σ</BLink>
        v{{VERSION_MAJOR}}.{{VERSION_MINOR}},
        <span class="gitinfo" :title="GIT_LONG_STR">
            <a :href="`https://github.com/model-railroad/conductor/tree/${GIT_BRANCH_STR}`" target="_blank">
                build {{GIT_BRANCH_STR}}
            </a>
            @
            <a :href="`https://github.com/model-railroad/conductor/commit/${GIT_HASH_STR}`" target="_blank">
              {{GIT_HASH_STR}}
            </a>
        </span>
      </BNavText>
    </BCollapse>
  </BNavbar>
</template>
